mongo:
  host: localhost
  
rabbit:
  host: localhost
  
server:
  port: 8080
  
spring:

  # APPLICATION TYPE
#  main:
#    web-application-type: reactive

  # MONGO
  data:
    mongodb:
      #host: 192.168.99.100
      host: ${mongo.host}
      port: 27017
      database: person

  # BINDER RABBIT
  rabbitmq:
    #host: 192.168.99.100
    host: ${rabbit.host}
    port: 5672
    username: guest
    password: guest
    
    
  cloud:
    stream:
      bindings:
        
        # SEND PERSON EVENT
        send-person-created-event:
          destination: person-created-event
        
        send-person-updated-event:
          destination: person-updated-event
          
        send-person-actived-event:
          destination: person-actived-event
        
        send-person-deleted-event:
          destination: person-deleted-event
          
        # SEND PERSONAL DOCUMENT EVENT
        send-personalDocument-created-event:
          destination: document-created-event
          
        send-personalDocument-updated-event:
          destination: document-updated-event
          
        send-personalDocument-expired-event:
          destination: document-expired-event
          
        send-personalDocument-cancelled-event:
          destination: document-cancelled-event
          
        # SEND CONTACT EVENT
        send-contact-created-event:
          destination: contact-created-event
          
        send-contact-changed-event:
          destination: contact-changed-event
          
        send-contact-availabilityChanged-event:
          destination: contact-availability-changed-event
          
        send-contact-deleted-event:
          destination: contact-deleted-event
          
        # SEND ADDRESS EVENT
        send-address-created-event:
          destination: address-created-event
          
        send-address-updated-event:
          destination: address-updated-event
          
        send-address-deleted-event:
          destination: address-deleted-event                         
          